
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, right, workspace, +1
bind = SUPER, left, workspace, -1
bind = SUPER, Q, exec, kitty
bind = SUPER, C, killactive,
bind = SUPER, M, exit,
bind = SUPER, W, exec, ags toggle wallpaper-manager && killall -SIGUSR1 waybar

input {
    kb_layout = latam
    numlock_by_default = true
}

bindel = SUPER, Up, exec, brightnessctl set 5%+
bindel = SUPER, Down, exec, brightnessctl set 5%-

bind = SUPER, B, exec, firefox
bind = SUPER, F, fullscreen, 0
bind = SUPER, Space, togglefloating,
bind = SUPER, D, exec, rofi -show drun -theme ~/.config/rofi/theme.rasi -display-drun ''
bind = SUPER, P, exec, ags toggle sidebar
# bind = , Print, exec, grim ~/Capturas/captura_$(date +%Y%m%d_%H%M%S).png

exec-once = thunar --daemon
exec-once = waybar
exec-once = hyprpaper
exec-once = ags run
exec-once = dunst

decoration {
    rounding = 10

    # Opacidad de las ventanas (0.85 significa 85% sólido, 15% transparente)
    active_opacity = 0.85
    inactive_opacity = 0.75
    fullscreen_opacity = 1.0

    blur {
        enabled = true
        size = 8
        passes = 4
        new_optimizations = true

        vibrancy = 0.1696
        vibrancy_darkness = 0.0
        new_optimizations = true
        xray = true
        ignore_opacity = true
    }
}

general {
    gaps_in = 4
    gaps_out = 8
}

bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bindel = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5% && ~/.config/waybar/scripts/volume.sh show
bindel = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5% && ~/.config/waybar/scripts/volume.sh show

xwayland {
    force_zero_scaling = true
}
exec-once = ~/.config/hypr/startup.sh

blurls = waybar
blurls = swaync-control-center
blurls = ags
blurls = wallpaper-manager
